Repository andbread/Andbread_Frontend, pull requests merged in 2025-03, with the labels that each got.

#46 [feature-21/nbread-modals] 모달 추가 구현 완료
  src/app/nbread/[nbreadId]/page.tsx
  src/app/nbread/create/page.tsx
  src/components/common/Modal/ExitEditConfirmModal.tsx
  src/components/common/Modal/NbreadInviteModal.tsx
  src/components/common/header/detailHeader.tsx
  src/components/nbread/nbreadParticipantsList.tsx
  tailwind.config.ts
Labels: ✨ Feature

#47 [feature 10/feat] 캘린더 기능 구현 완료
  src/app/calendar/page.tsx
  src/components/calendar/calendar.tsx
  src/components/calendar/chargePlanCard.tsx
  src/components/home/NbreadCard.tsx
  src/lib/nbread/fetchNbreadData.ts
  src/stores/useNbreadPaymentState.tsx
Labels: ✨ Feature

#49 [feature-17/feat] 홈 페이지 결제 인원 기능 구현
  src/components/home/NbreadCard.tsx
  src/lib/nbread/getUserNbread.ts
  src/types/nbread.ts
Labels: ✨ Feature

#50 [feature-22/get-nbread-record] 엔빵 납부 여부 불러오기 기능 구현
  src/app/nbread/[nbreadId]/page.tsx
  src/components/home/MyNbreadList.tsx
  src/components/home/NbreadCard.tsx
  src/components/nbread/nbreadParticipantCard.tsx
  src/components/nbread/nbreadParticipantsList.tsx
  src/lib/nbreadRecord/getNbreadRecords.ts
  src/lib/nbreadRecord/index.ts
  src/types/nbread.ts
Labels: ✨ Feature

#51 [feature-18/user-delete-account] 회원탈퇴 기능 구현 + 로그인 콜백 페이지 로딩 스피너 추가
  package-lock.json
  package.json
  src/app/auth/callback/page.tsx
  src/app/mypage/page.tsx
  src/components/common/spinner/Spinner.tsx
  src/components/mypage/Manage.tsx
  src/components/user/DeleteAccountModal.tsx
  src/lib/auth.ts
  src/lib/supabaseAdminClient.ts
  src/lib/supabaseClient.ts
  src/styles/globals.css
Labels: ✨ Feature

#54 [feature-24/style] 홈 페이지, 엔빵 생성 페이지, 초대 수락 페이지 퍼블리싱 수정 및 기타 수정사항 반영
  src/app/home/page.tsx
  src/app/inviteAccept/page.tsx
  src/app/nbread/[nbreadId]/page.tsx
  src/app/nbread/create/page.tsx
  src/app/nbread/preview/page.tsx
  src/assets/logo/nbread-logo-text.svg
  src/assets/logo/nbread-logo.svg
  src/assets/logo/nbreads.svg
  src/components/common/card/dashlineCard.tsx
  src/components/common/nbreadImage/NbreadsImage.tsx
  src/components/common/spinner/Spinner.tsx
  src/components/home/AddLogButton.tsx
  src/components/home/Emptylog.tsx
  src/components/home/Header.tsx
  src/components/home/MonthlyNbread.tsx
  src/components/home/MyNbread.tsx
  src/components/home/MyNbreadList.tsx
  src/components/home/NbreadCard.tsx
  src/components/inviteAccept/InviteAcceptButton.tsx
  src/components/inviteAccept/InviteAcceptTitle.tsx
  src/components/nbread/nbreadParticipantCard.tsx
  src/lib/nbread/getUserNbread.ts
  src/styles/globals.css
  src/types/nbread.ts
  tailwind.config.ts
Labels: 🎨 HTML&CSS, 🐞 BugFix

#57 [feature-23/create-invite-link] 친구 초대 수락 기능 구현
  global.d.ts
  src/app/auth/callback/page.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/nbread/[nbreadId]/page.tsx
  src/app/nbread/detail/page.tsx
  src/components/calendar/chargePlanCard 2.tsx
  src/components/calendar/chargePlanCard.tsx
  src/components/common/Modal/NbreadInviteModal.tsx
  src/components/common/card/dashlineCard.tsx
  src/components/inviteAccept/InvitationToNbreadModal 2.tsx
  src/components/inviteAccept/InvitationToNbreadModal.tsx
  src/components/inviteAccept/InviteAcceptButton.tsx
  src/components/inviteAccept/InviteAcceptModal.tsx
  src/components/inviteAccept/InviteAcceptTitle.tsx
  src/components/nbread/nbreadParticipantCard.tsx
  src/components/nbread/nbreadParticipantsList.tsx
  src/components/user/LoginButton.tsx
  src/components/user/LogoutModal.tsx
  src/lib/auth.ts
  src/lib/nbread/getNbread.ts
  src/lib/nbread/insertLink 2.ts
  src/lib/nbread/insertLink.ts
  src/lib/participant/getParticipants.ts
  src/lib/participant/insertParticipant.ts
  src/lib/supabaseClient.ts
  src/types/nbread.ts
Labels: ✨ Feature

#58 [feature-24/style] 퍼블리싱 수정 및 기타 수정사항 반영
  src/app/calendar/page.tsx
  src/app/favicon.ico
  src/app/home/page.tsx
  src/app/icon.ico
  src/app/inviteAccept/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/protectRoute.tsx
  src/assets/logo/nbread-text.svg
  src/assets/logo/nbreads-not-found.svg
  src/components/calendar/calendar.tsx
  src/components/calendar/chargePlanCard 2.tsx
  src/components/common/Modal/LoginConfirmModal.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/NbreadInviteModal.tsx
  src/components/home/Header.tsx
  src/components/inviteAccept/InvitationToNbreadModal 2.tsx
  src/components/inviteAccept/InvitationToNbreadModal.tsx
  src/components/inviteAccept/InviteAcceptModal.tsx
  src/components/inviteAccept/InviteAcceptTitle.tsx
  src/components/mypage/Manage.tsx
  src/components/mypage/MenuList.tsx
  src/components/mypage/MyInfo.tsx
  src/components/user/LoginButton.tsx
  src/lib/nbread/insertLink 2.ts
  src/lib/participant/insertParticipant.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature, 🐞 BugFix

#59 [feature-26/mypage-refactor] 마이페이지 버그 수정, 엔빵 합계 확인하기 구현
  src/components/common/Modal/MyNbreadSumModal.tsx
  src/components/mypage/MyInfo.tsx
  src/lib/nbread/getUserTotalNbreadAmount.ts
Labels: ✨ Feature, 🐞 BugFix

#61 [feature-25/delete-participant] 엔빵 멤버 삭제하기, 엔빵 탈퇴하기 기능 구현
  src/app/nbread/[nbreadId]/page.tsx
  src/components/common/Modal/DeleteParticipantModal.tsx
  src/components/common/Modal/LoginConfirmModal.tsx
  src/components/common/Modal/MyNbreadSumModal.tsx
  src/components/common/Modal/QuitNbreadModal.tsx
  src/components/inviteAccept/InvitationToNbreadModal.tsx
  src/components/nbread/nbreadParticipantCard.tsx
  src/components/nbread/nbreadParticipantsList.tsx
  src/components/user/LogoutModal.tsx
  src/lib/participant/deleteParticipant.ts
  src/lib/participant/index.ts
Labels: ✨ Feature

#71 [hotfix-v1.0/css-scroll] div overflow-hidden 속성 제거 및 body overscroll-contain으로 변경
  src/styles/globals.css
Labels: 🐞 BugFix

#72 [release-v1.0/hotfix] div overflow-hidden 속성 제거 및 body overscroll-contain으로 변경
  src/styles/globals.css
Labels: 🌏 Deploy, 🐞 BugFix

#74 [hotfix-v1.0/css-scroll] 페이지 내 중복 스크롤 오류 해결 및 스크롤바 숨김 처리
  src/app/login/page.tsx
  src/app/nbread/[nbreadId]/page.tsx
  src/styles/globals.css
Labels: 🐞 BugFix

#75 [release-v1.0/hotfix] 페이지 중첩 스크롤 해결 및 스크롤바 숨김 처리
  src/app/login/page.tsx
  src/app/nbread/[nbreadId]/page.tsx
  src/styles/globals.css
Labels: 🌏 Deploy, 🐞 BugFix

#77 [release-v1.0/hotfix] 초대 수락 페이지 레이아웃 깨짐 수정
  src/app/inviteAccept/page.tsx
Labels: 🌏 Deploy, 🐞 BugFix

#82 chore: release v1.0 ~ v1.2까지 변경사항을 develop에 업데이트
  README.md
  public/assets/logo/open-graph-logo.png
  src/app/inviteAccept/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/nbread/[nbreadId]/page.tsx
  src/components/calendar/chargePlanCard.tsx
  src/components/nbread/nbreadEditCard.tsx
  src/lib/GoogleAnalytics.tsx
  src/lib/nbread/insertLink.ts
  src/styles/globals.css
Labels: 🌏 Deploy, 📃 Docs

#86 [release-v1.4] 홈 페이지 이번 달 엔빵 수정
  src/app/calendar/page.tsx
  src/app/page.tsx
  src/lib/nbread/getUserNbread.ts
Labels: ✨ Feature, 🐞 BugFix
