Repository andbread/Andbread_Frontend, pull requests merged in 2025-02, with the labels that each got.

#5 [feature-05/chore] 라우팅 디렉토리 경로 수정
  src/app/login/page.tsx
  src/components/login/LoginButton.tsx
  src/pages/blog/page.tsx
Labels: 🔨 Refactor

#6 [feature-01/setting] Github, Tailwind 기본 스타일 등 개발 환경 설정 #2
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/labels.json
  .github/pull_request_template.md
  .prettierrc
  global.d.ts
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/blog/blogPostButton.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ⚙ Setting

#7 [feature-01/setting] Issue 템플릿이 적용되지 않는 문제 해결
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
Labels: ⚙ Setting

#10 [feature-06/style] svg 아이콘 사용 관련 설정 및 Icon 컴포넌트 구현
  next.config.ts
  package-lock.json
  package.json
  src/app/page.tsx
  src/assets/avatar.svg
  src/assets/icons/angle-left.svg
  src/assets/icons/angle-right.svg
  src/assets/icons/badge.svg
  src/assets/icons/calendar.svg
  src/assets/icons/check.svg
  src/assets/icons/copy.svg
  src/assets/icons/cross-fill.svg
  src/assets/icons/cross.svg
  src/assets/icons/login-google.svg
  src/assets/icons/login-kakao.svg
  src/assets/icons/plus.svg
  src/assets/icons/warning.svg
  src/components/common/icon/Icon.tsx
Labels: ⚙ Setting, 🎨 HTML&CSS

#11 [feature-05/style] 로고 미포함 로그인 페이지 퍼블리싱
  package-lock.json
  package.json
  src/app/login/page.tsx
  src/components/login/LoginButton.tsx
Labels: 🎨 HTML&CSS

#15 [feature-06/style] 엔빵 등록하기 페이지 퍼블리싱
  next.config.ts
  package-lock.json
  package.json
  src/app/nbread/create/page.tsx
  src/app/nbread/preview/page.tsx
  src/app/page.tsx
  src/components/common/avatar/avatar.tsx
  src/components/common/card/dashlineCard.tsx
  src/components/common/header/detailHeader.tsx
  src/components/common/icon/Icon.tsx
  src/components/common/tab/tab.tsx
  src/components/common/tabbar/tabbar.tsx
  src/components/nbread/nbreadCard.tsx
  src/components/nbread/nbreadEditCard.tsx
  src/components/nbread/nbreadParticipantCard.tsx
  src/stores/useNbreadStore.tsx
  src/styles/globals.css
  src/types/nbread.ts
Labels: 🎨 HTML&CSS

#17 [feature 03/style] 캘린더 페이지 퍼블리싱 완료
  package.json
  src/app/calendar/page.tsx
  src/components/calendar/calendar.tsx
  src/components/calendar/chargePlanCard.tsx
  src/components/common/icon/Icon.tsx
Labels: 🎨 HTML&CSS

#19 [feature-07/style] 홈 페이지 퍼블리싱
  src/app/home/page.tsx
  src/components/home/AddLogButton.tsx
  src/components/home/Emptylog.tsx
  src/components/home/Header.tsx
Labels: 🎨 HTML&CSS

#21 [feature-09/style] 엔빵 상세보기/수정하기 페이지 퍼블리싱
  src/app/nbread/create/page.tsx
  src/app/nbread/detail/page.tsx
  src/components/common/checkbox/checkbox.tsx
  src/components/common/header/detailHeader.tsx
  src/components/common/tab/tab.tsx
  src/components/common/tabbar/tabbar.tsx
  src/components/nbread/nbreadEditCard.tsx
  src/components/nbread/nbreadParticipantCard.tsx
  src/components/nbread/nbreadParticipantsList.tsx
  src/styles/globals.css
  src/types/nbread.ts
  src/types/user.ts
Labels: 🎨 HTML&CSS

#24 [feature-08/feat] 소셜 로그인 기능 구현
  package-lock.json
  src/app/auth/callback/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/login/LoginButton.tsx
  src/lib/auth.ts
  src/lib/supabaseClient.ts
  src/stores/useAuthStore.tsx
  src/types/nbread.ts
  src/types/user.ts
Labels: ✨ Feature

#25 [feature-11/style] 마이페이지 퍼블리싱
  src/app/mypage/page.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/MyNbreadSumModal.tsx
  src/components/mypage/Manage.tsx
  src/components/mypage/MenuList.tsx
  src/components/mypage/MyInfo.tsx
Labels: 🎨 HTML&CSS

#27 [feature-13/feat] 마이 페이지 계정 정보 불러오기 기능 구현
  next.config.ts
  src/components/home/Header.tsx
  src/components/mypage/MyInfo.tsx
Labels: ✨ Feature

#28 [feature-13/feat] 마이 페이지 계정 정보 불러오기 기능 구현
  next.config.ts
  src/components/common/avatar/avatar.tsx
  src/components/mypage/MyInfo.tsx
Labels: 🔨 Refactor

#29 [feature-12/nbread-craete] 엔빵 생성하기 기능 구현
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/nbread/create/page.tsx
  src/app/nbread/preview/page.tsx
  src/components/common/avatar/avatar.tsx
  src/components/common/toast/Toast.tsx
  src/components/nbread/nbreadCard.tsx
  src/components/nbread/nbreadParticipantCard.tsx
  src/lib/nbread/deleteNbread.ts
  src/lib/nbread/index.ts
  src/lib/nbread/insertNbread.ts
  src/lib/participant/index.ts
  src/lib/participant/insertParticipant.ts
  src/lib/supabaseClient.ts
  src/stores/useNbreadStore.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature

#33 [feature-15/feat] 등록한 엔빵 홈 페이지 표시하기 구현
  src/app/home/page.tsx
  src/components/home/Header.tsx
  src/components/home/MonthlyNbread.tsx
  src/components/home/MyNbread.tsx
  src/components/home/MyNbreadList.tsx
  src/components/home/NbreadCard.tsx
  src/components/home/NbreadList.tsx
  src/lib/nbread/getUserNbread.ts
Labels: ✨ Feature

#34 [feature-02/style] 친구 초대 수락 페이지 퍼블리싱
  src/app/inviteAccept/page.tsx
  src/components/common/Modal/Modal.tsx
  src/components/inviteAccept/InviteAcceptButton.tsx
  src/components/inviteAccept/InviteAcceptModal.tsx
  src/components/inviteAccept/InviteAcceptTitle.tsx
  src/types/nbread.ts
Labels: 🎨 HTML&CSS

#36 [feature-14/nbread-update] 엔빵 조회 기능 및 홈페이지 수정
  eslint.config.mjs
  src/app/home/page.tsx
  src/components/home/MonthlyNbread.tsx
  src/components/home/MyNbreadList.tsx
  src/components/home/NbreadCard.tsx
  src/components/home/NbreadList.tsx
  src/lib/nbread/getUserNbread.ts
  src/lib/participant/getParticipants.ts
  src/lib/participant/insertParticipant.ts
  src/types/nbread.ts
  src/types/supabase.ts
Labels: ✨ Feature

#38 [feature-16/user-logout] 로그아웃 기능 구현
  src/app/auth/callback/page.tsx
  src/app/login/page.tsx
  src/components/mypage/Manage.tsx
  src/components/user/DeleteAccountModal.tsx
  src/components/user/LoginButton.tsx
  src/components/user/LogoutModal.tsx
  src/lib/auth.ts
Labels: ✨ Feature

#41 [feature-14/nbread-update] 엔빵 상세페이지 조회 기능 구현
  src/app/nbread/[nbreadId]/page.tsx
  src/app/nbread/detail/page.tsx
  src/components/home/MonthlyNbread.tsx
  src/components/home/MyNbread.tsx
  src/components/home/MyNbreadList.tsx
  src/components/home/NbreadCard.tsx
  src/components/home/NbreadList.tsx
  src/components/nbread/nbreadCard.tsx
  src/components/nbread/nbreadParticipantsList.tsx
  src/lib/nbread/getNbread.ts
  src/styles/globals.css
  src/types/user.ts
Labels: ✨ Feature

#44 [feature-20/nbread-record-update] 엔빵 납부 여부 업데이트 기능 구현 완료
  src/app/nbread/[nbreadId]/page.tsx
  src/components/common/checkbox/checkbox.tsx
  src/components/nbread/nbreadParticipantCard.tsx
  src/components/nbread/nbreadParticipantsList.tsx
  src/lib/nbread/getNbread.ts
  src/lib/nbread/getUserNbread.ts
  src/lib/nbreadRecord/index.ts
  src/lib/nbreadRecord/updateNbreadRecord.ts
  src/types/nbread.ts
Labels: ✨ Feature
